name: Build Avalonia UI App (Windows)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish mpv_audio.csproj -c Release -o publish_output

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MPVAudio-Windows
          path: publish_output
